name: Build and deploy WAR app to Azure Web App - MWO-TGL-SBX-POC
on: push
jobs:
  wget:
    runs-on: ubuntu-latest
    steps:
    - name: wget
      uses: wei/wget@v1
      with:
        args: -O downloads/sample.war https://tomcat.apache.org/tomcat-8.5-doc/appdev/sample/sample.war

